
name: Deploy to AWS

# on: 
#   push: 
#     branches: 
#       - main

on: workflow_dispatch

jobs:
  workflow-test: # Arbitrary name
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      
      - name: Run a script that echoes a test string
        run: echo "Testing 123..."
